# specify each hardware identifier in square brackets
[ota-ce-device]
target_format = "BINARY"
generate_dif = true

# required metadata specifying update target
[ota-ce-device.to]
name = "cevanou"
version = "2"
length = 6
hash = "528660877355408985fedd9ea2cf6b289960a850d9f277070376d333363da57c"
method = "sha256"
