# specify each hardware identifier in square brackets
[ota-ce-device]
target_format = "BINARY"
generate_dif = true

# required metadata specifying update target
[ota-ce-device.to]
name = "cevaFrum"
version = "2"
length = 7
hash = "61b4c705859f4158d38090c1e38e8fdc4f3d29db007f012766276aa498835cf6"
method = "sha256"
